var QUIZ_CONFIG = {
  PROJECT_NAME: 'Sportbud Meeting',
  MENU_NAME: 'Quiz Tools',
  MENU_ACTION_GENERATE: 'Generate Presentation',
  MENU_ACTION_REFRESH_STANDINGS: 'Refresh Standings Slides',
  TEMPLATE_PRESENTATION_ID: '1oua7aM9tNjeBNYenfJTeXLgCkZEXLQBNoNp-fT5p_Q8',
  BASE_SHEET_NAME: 'Základní část',
  SHEET_COLUMNS: {
    ORDER: 0,
    TEXT: 1,
    ANSWER: 2
  },
  RULES: {
    QUESTIONS_PER_TOPIC: 4,
    TOPICS_PER_ROUND: 2,
    BONUS_PER_ROUND: 1
  },
  TEMPLATE_MARKERS: {
    TOPIC: '{{QUIZ_TOPIC_SLIDE}}',
    QUESTION: '{{QUIZ_QUESTION_SLIDE}}',
    ANSWER: '{{QUIZ_ANSWER_SLIDE}}',
    ROUND_STANDINGS: '{{ROUND_STANDINGS_SLIDE}}',
    BEER_BONUS_QUESTION: '{{BEER_BONUS_QUESTION_SLIDE}}',
    BEER_BONUS_ANSWER: '{{BEER_BONUS_ANSWER_SLIDE}}'
  },
  TEMPLATE_TOKENS: {
    ROUND_TITLE: '{{ROUND_TITLE}}',
    TOPIC_TITLE: '{{TOPIC_TITLE}}',
    QUESTION_NUMBER: '{{QUESTION_NUMBER}}',
    QUESTION_LABEL: '{{QUESTION_LABEL}}',
    QUESTION_TEXT: '{{QUESTION_TEXT}}',
    ANSWER_LABEL: '{{ANSWER_LABEL}}',
    ANSWER_TEXT: '{{ANSWER_TEXT}}'
  },
  STANDINGS: {
    SPREADSHEET_ID: '1GittrOX9iyJLoTlSG79l9eO1LGRacrFqBiRUnrd2QH8',
    SHEET_NAME: 'Aktuální kolo',
    FIRST_DATA_ROW: 2,
    MAX_TEAMS: 14,
    POSITION_COLUMN: 1,
    TEAM_COLUMN: 2,
    POINTS_COLUMN: 10,
    META_SHEET_NAME: '__sportbud_meta',
    LAST_PRESENTATION_PROPERTY: 'LAST_GENERATED_PRESENTATION_ID',
    LAST_STANDINGS_SLIDES_PROPERTY: 'LAST_GENERATED_STANDINGS_SLIDE_IDS'
  },
  RISK: {
    SHEET_NAME: 'Riskuj',
    TOPIC_COUNT: 6,
    QUESTIONS_PER_TOPIC: 5,
    BACK_LINK_TEXT: 'Zpátky k výběru',
    BACK_LINK_COLOR: '#FFFFFF',
    TEMPLATE_MARKERS: {
      MENU: '{{RISK_MENU_SLIDE}}',
      QUESTION: '{{RISK_QUESTION_SLIDE}}',
      ANSWER: '{{RISK_ANSWER_SLIDE}}'
    },
    TEMPLATE_TOKENS: {
      TOPIC_TITLE: '{{RISK_TOPIC_TITLE}}',
      POINTS_LABEL: '{{RISK_POINTS_LABEL}}',
      QUESTION_TEXT: '{{RISK_QUESTION_TEXT}}',
      ANSWER_TEXT: '{{RISK_ANSWER_TEXT}}'
    }
  }
};
