var QUIZ_CONFIG = {
  PROJECT_NAME: 'Sportbud Meeting',
  MENU_NAME: 'Quiz Tools',
  MENU_ACTION_GENERATE: 'Generate Presentation',
  TEMPLATE_PRESENTATION_ID: '1oua7aM9tNjeBNYenfJTeXLgCkZEXLQBNoNp-fT5p_Q8',
  SHEET_COLUMNS: {
    ORDER: 0,
    TEXT: 1,
    ANSWER: 2
  },
  RULES: {
    QUESTIONS_PER_TOPIC: 4,
    TOPICS_PER_ROUND: 2,
    BONUS_PER_ROUND: 1
  },
  TEMPLATE_MARKERS: {
    TOPIC: '{{QUIZ_TOPIC_SLIDE}}',
    QUESTION: '{{QUIZ_QUESTION_SLIDE}}',
    ANSWER: '{{QUIZ_ANSWER_SLIDE}}'
  },
  TEMPLATE_TOKENS: {
    ROUND_TITLE: '{{ROUND_TITLE}}',
    TOPIC_TITLE: '{{TOPIC_TITLE}}',
    QUESTION_NUMBER: '{{QUESTION_NUMBER}}',
    QUESTION_LABEL: '{{QUESTION_LABEL}}',
    QUESTION_TEXT: '{{QUESTION_TEXT}}',
    ANSWER_LABEL: '{{ANSWER_LABEL}}',
    ANSWER_TEXT: '{{ANSWER_TEXT}}'
  }
};
